package com.bhop4real.proton.client.util;

import java.util.Random;

/**
 * Utility for lightweight pseudo-random generation using java.util.Random.
 * Provides the same convenience helpers as {@link SecureRandomUtil} but
 * without the cryptographic overhead.
 */
public final class RandomUtil
{
    private static final Random RANDOM = new Random();

    private RandomUtil() {} // Prevent instantiation

    /**
     * Returns a pseudo-random integer in the range [min, max).
     * If min >= max, min is returned.
     */
    public static int nextInt(int min, int max)
    {
        if (min >= max)
        {
            return min;
        }
        return RANDOM.nextInt(max - min) + min;
    }

    /**
     * Returns a pseudo-random double in the range [0.0, 1.0).
     */
    public static double nextDouble()
    {
        return RANDOM.nextDouble();
    }

    /**
     * Returns a pseudo-random double in the range [min, max).
     * If min >= max, min is returned.
     */
    public static double nextDouble(double min, double max)
    {
        if (min >= max)
        {
            return min;
        }
        return RANDOM.nextDouble() * (max - min) + min;
    }

    /**
     * Returns a pseudo-random long value generated by java.util.Random.
     */
    public static long nextLong()
    {
        return RANDOM.nextLong();
    }

    /**
     * Returns a pseudo-random boolean value.
     */
    public static boolean nextBoolean()
    {
        return RANDOM.nextBoolean();
    }

    /**
     * Returns a pseudo-random Gaussian (normal) distributed double
     * with mean 0 and standard deviation 1.
     */
    public static double nextGaussian()
    {
        return RANDOM.nextGaussian();
    }

    /**
     * Allows deterministic behavior for testing.
     */
    public static void setSeed(long seed)
    {
        RANDOM.setSeed(seed);
    }
}

